# This is a basic workflow to help you get started with Actions

name: CI
on: 
  push:
   branches:
    - main
    - develop
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
       - uses: actions/checkout@v2
       - uses: actions/setup-node@v1
         with:
             node-version: 14.16.1
       - uses: actions/setup-java@v1
         with:
             java-version: '11.x'
       - name: Install node.js packages
         run: npm install
       - name: Install test ci
         run: npm run ci:frontend:test
       - name: test backend
         run: chmod +x mvnw && npm run ci:backend:test
       - name: Test Integration
         run: ./mvnw -ntp verify -DskipTests --batch-mode "-Pprod" "-Pe2e" "-Denforcer.skip=true"*
       - name: Prepare docker
         run: npm run ci:e2e:prepare:docker
       - name: Lance test e2e
         run: npm run ci:e2e:run
         env: 
          JHI_E2E_HEADLESS: true
       - name: Stop docker et nettoie tout
         run: npm run ci:e2e:teardown
  deploy:
      needs: test
    # The type of runner that the job will run on
      runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: deploy on heroku
        run: ./mvnw -ntp com.heroku.sdk:heroku-maven-plugin:2.0.5:deploy -DskipTests -Pprod -Dheroku.buildpacks=heroku/jvm -Dheroku.appName=tpjhipster
        env:
         HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
